# Chave da API para o modelo de linguagem
GEMINI_API_KEY = "AIzaSyDLNPxfhsgQa_GQwQ5NMf8wKl2NQn5DANA"

# Conexão com o banco de dados Supabase PostgreSQL
[connections.supabase]
url = "postgresql://postgres.uzckxgfhsfzulqqtxuqe:Freitxs262004@aws-1-sa-east-1.pooler.supabase.com:6543/postgres"

# Chave da API para o MDM Pulsus
PULSUS_API_KEY = "bjnB2X2SLXgcHoxjvUEJci2YgBeKzzDqycKFNFxaDp2sncER6tZRUTgGFVNw"